---
 - hosts: dbserver
   become: true
   tasks:

   - name: Installing Apache2
     apt:
        name: apache2
   - name: Ping
     ansible.builtin.ping:
   - name: update repository index
     apt: 
       update_cache: yes
   - name: install apache2 package
     apt: 
       name: apache2
   - name: add PHP support for apache
     apt: 
       name: libapache2-mod-php
